-- gogooo_dev.CODE definition

CREATE TABLE `CODE` (
  `CODE_ID` varchar(50) NOT NULL,
  `CODE_TPCD` varchar(8) NOT NULL,
  `CODE_NM` varchar(50) DEFAULT NULL,
  `VALUE` varchar(50) DEFAULT NULL,
  `ORDER_SEQ` int(11) DEFAULT 0,
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT NULL,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`CODE_ID`,`CODE_TPCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- gogooo_dev.CODE_DETAIL definition

CREATE TABLE `CODE_DETAIL` (
  `CODE_ID` varchar(50) NOT NULL,
  `CODE_TPCD` varchar(8) NOT NULL,
  `CODE_DETAIL_ID` varchar(50) NOT NULL,
  `CODE_DETAIL_TPCD` varchar(8) NOT NULL,
  `CODE_DETAIL_NM` varchar(50) NOT NULL,
  `VALUE` varchar(50) NOT NULL,
  `ORDER_SEQ` int(11) DEFAULT 0,
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT 0,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`CODE_ID`,`CODE_TPCD`,`CODE_DETAIL_ID`,`CODE_DETAIL_TPCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- gogooo_dev.COMPANY definition

CREATE TABLE `COMPANY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(120) NOT NULL,
  `DOMAIN` varchar(120) NOT NULL,
  `COMPANY_TPCD` varchar(4) NOT NULL,
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT NULL,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4;


-- gogooo_dev.INTEREST_ICON definition

CREATE TABLE `INTEREST_ICON` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `IMG_FILE_NM` varchar(5000) DEFAULT NULL,
  `INTEREST_TPCD` char(2) DEFAULT '00',
  `INTEREST_SEQ` int(11) DEFAULT NULL,
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT NULL,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4;


-- gogooo_dev.JOIN_APPLICANT definition

CREATE TABLE `JOIN_APPLICANT` (
  `EMAIL` varchar(120) NOT NULL,
  `APPLY_SEQ` int(11) NOT NULL,
  `PASSWORD` varchar(120) DEFAULT NULL,
  `APPLICATION_DTTM` datetime DEFAULT current_timestamp(),
  `APPROVAL_DTTM` datetime DEFAULT NULL,
  `TOKEN_KEY` varchar(20) NOT NULL,
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT NULL,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`EMAIL`,`APPLY_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- gogooo_dev.LIST_LEADING_ICON definition

CREATE TABLE `LIST_LEADING_ICON` (
  `CODE_ID` varchar(50) NOT NULL,
  `CODE_TPCD` varchar(50) NOT NULL,
  `CODE_DETAIL_ID` varchar(50) NOT NULL,
  `CODE_DETAIL_TPCD` varchar(50) NOT NULL,
  `IMG_FILE_NM` varchar(5000) NOT NULL,
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT 0,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`CODE_ID`,`CODE_TPCD`,`CODE_DETAIL_ID`,`CODE_DETAIL_TPCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- gogooo_dev.NOTICE definition

CREATE TABLE `NOTICE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(5000) DEFAULT NULL,
  `CONTENTS` varchar(5000) DEFAULT NULL,
  `NOTICE_DATE` datetime DEFAULT current_timestamp(),
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT 0,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;


-- gogooo_dev.PROFILE_ICON definition

CREATE TABLE `PROFILE_ICON` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `IMG_FILE_NM` varchar(5000) DEFAULT NULL,
  `PROFILE_TPCD` varchar(8) DEFAULT NULL,
  `PROFILE_SEQ` int(11) DEFAULT NULL,
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT 0,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4;


-- gogooo_dev.`USER` definition

CREATE TABLE `USER` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(120) NOT NULL,
  `NAME` varchar(120) DEFAULT NULL,
  `PASSWORD` varchar(120) DEFAULT NULL,
  `SIGN_UP_DTTM` datetime DEFAULT current_timestamp(),
  `LAST_LOGIN_DTTM` datetime DEFAULT NULL,
  `WITHDRAWAL_DTTM` datetime DEFAULT NULL,
  `PROFILE_ICON_ID` int(11) DEFAULT NULL,
  `STAR_CODE` varchar(6) DEFAULT NULL,
  `GRAVITY_VALUE` int(11) DEFAULT 1,
  `COMPANY_ID` int(11) DEFAULT 1,
  `SEX` varchar(2) DEFAULT NULL,
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT NULL,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`),
  KEY `User_CompanyId` (`COMPANY_ID`),
  KEY `PROFILE_ICON_ID` (`PROFILE_ICON_ID`),
  CONSTRAINT `USER_ibfk_1` FOREIGN KEY (`PROFILE_ICON_ID`) REFERENCES `PROFILE_ICON` (`ID`),
  CONSTRAINT `USER_ibfk_2` FOREIGN KEY (`PROFILE_ICON_ID`) REFERENCES `PROFILE_ICON` (`ID`),
  CONSTRAINT `User_CompanyId` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4;


-- gogooo_dev.USER_DISLIKE_STAR_USER definition

CREATE TABLE `USER_DISLIKE_STAR_USER` (
  `USER_ID` int(11) unsigned NOT NULL,
  `STAR_USER_ID` int(11) unsigned NOT NULL,
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT 0,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`USER_ID`,`STAR_USER_ID`),
  KEY `STAR_USER_ID` (`STAR_USER_ID`),
  CONSTRAINT `USER_DISLIKE_STAR_USER_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`),
  CONSTRAINT `USER_DISLIKE_STAR_USER_ibfk_2` FOREIGN KEY (`STAR_USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- gogooo_dev.USER_INTEREST definition

CREATE TABLE `USER_INTEREST` (
  `USER_ID` int(11) unsigned NOT NULL,
  `INTEREST_ID` int(11) NOT NULL,
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT NULL,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`USER_ID`,`INTEREST_ID`),
  KEY `UserInterest_InterestId` (`INTEREST_ID`),
  CONSTRAINT `USER_INTEREST_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- gogooo_dev.USER_LIKE_STAR_USER definition

CREATE TABLE `USER_LIKE_STAR_USER` (
  `USER_ID` int(11) unsigned NOT NULL,
  `STAR_USER_ID` int(11) unsigned NOT NULL,
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT NULL,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`USER_ID`,`STAR_USER_ID`),
  KEY `LikeStarUser_StarUserId` (`STAR_USER_ID`),
  CONSTRAINT `USER_LIKE_STAR_USER_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`),
  CONSTRAINT `USER_LIKE_STAR_USER_FK_1` FOREIGN KEY (`STAR_USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- gogooo_dev.FEED definition

CREATE TABLE `FEED` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `FEED_TPCD` varchar(1) NOT NULL,
  `CONTENT` varchar(5000) DEFAULT NULL,
  `IMAGE_URL` varchar(200) DEFAULT NULL,
  `USER_ID` int(11) unsigned NOT NULL,
  `REGI_DTTM` varchar(14),
  `ALT_TPCD` varchar(1) DEFAULT '1',
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`),
  KEY `FEED_FK` (`USER_ID`),
  CONSTRAINT `FEED_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COMMENT='피드 게시물 정보';


-- gogooo_dev.FEED_COMMENT definition

CREATE TABLE `FEED_COMMENT` (
  `FEED_ID` int(11) unsigned NOT NULL,
  `GROUP_NUM` int(11) NOT NULL,
  `SUB_NUM` int(11) NOT NULL,
  `USER_ID` int(11) unsigned NOT NULL,
  `ALT_TPCD` varchar(1) DEFAULT '1',
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`FEED_ID`,`GROUP_NUM`,`SUB_NUM`),
  KEY `FEED_COMMENT_FK_1` (`USER_ID`),
  CONSTRAINT `FEED_COMMENT_FK` FOREIGN KEY (`FEED_ID`) REFERENCES `FEED` (`ID`),
  CONSTRAINT `FEED_COMMENT_FK_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='피드 댓 정보';


-- gogooo_dev.MEETING definition

CREATE TABLE `MEETING` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ORGANIZER_ID` int(11) unsigned DEFAULT NULL,
  `INTEREST_CATEGORY_TPCD` varchar(8) DEFAULT NULL,
  `INTEREST_ICON_ID` int(11) DEFAULT NULL,
  `MEETING_NM` varchar(120) NOT NULL,
  `START_DTTM` datetime DEFAULT current_timestamp(),
  `MIN_USER_NUM` int(11) DEFAULT 2,
  `MAX_USER_NUM` int(11) DEFAULT 2,
  `MIN_ENTRY_FEE` int(11) DEFAULT 0,
  `MAX_ENTRY_FEE` int(11) DEFAULT 0,
  `DESCRIPTION` varchar(5000) DEFAULT NULL,
  `LOCATION_TITLE` varchar(50) DEFAULT NULL,
  `LOCATION_ADDRESS` varchar(300) DEFAULT NULL,
  `LONGITUDE` varchar(30) DEFAULT NULL,
  `LATITUDE` varchar(30) DEFAULT NULL,
  `PROS_TPCD` char(1) DEFAULT '1',
  `REGI_DTTM` varchar(14),
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT NULL,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`),
  KEY `Meeting_OrganizerId` (`ORGANIZER_ID`),
  KEY `INTEREST_ICON_ID` (`INTEREST_ICON_ID`),
  CONSTRAINT `MEETING_FK` FOREIGN KEY (`ORGANIZER_ID`) REFERENCES `USER` (`ID`),
  CONSTRAINT `MEETING_ibfk_1` FOREIGN KEY (`INTEREST_ICON_ID`) REFERENCES `INTEREST_ICON` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8mb4 COMMENT='PROS_TPCD 1: 신청중, 2:모집마감, 3:모임완료, 4:모임취소';


-- gogooo_dev.MEETING_HASHTAG definition

CREATE TABLE `MEETING_HASHTAG` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `MEETING_ID` int(11) unsigned DEFAULT NULL,
  `TAG_NM` varchar(100) DEFAULT NULL,
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT NULL,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`),
  KEY `MeetingHashtag_MeetingId` (`MEETING_ID`),
  CONSTRAINT `MEETING_HASHTAG_FK` FOREIGN KEY (`MEETING_ID`) REFERENCES `MEETING` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8mb4;


-- gogooo_dev.PUSH_CHAT definition

CREATE TABLE `PUSH_CHAT` (
  `MEETING_ID` int(11) unsigned NOT NULL,
  `MESSAGE_ID` int(11) unsigned NOT NULL,
  `RECEIVER_ID` int(11) unsigned NOT NULL,
  `SENDER_ID` int(11) unsigned DEFAULT NULL,
  `PHOTO_YN` tinyint(1) DEFAULT NULL,
  `PAYLOAD` varchar(2000) DEFAULT NULL,
  `ALT_TPCD` char(1) DEFAULT '1',
  `INPUT_DTTM` int(11) unsigned NOT NULL,
  `FIRST_REGI_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`MEETING_ID`,`MESSAGE_ID`,`RECEIVER_ID`),
  KEY `PUSH_CHAT_FK2` (`RECEIVER_ID`),
  KEY `PUSH_CHAT_FK3` (`SENDER_ID`),
  CONSTRAINT `PUSH_CHAT_FK` FOREIGN KEY (`MEETING_ID`) REFERENCES `MEETING` (`ID`),
  CONSTRAINT `PUSH_CHAT_FK2` FOREIGN KEY (`RECEIVER_ID`) REFERENCES `USER` (`ID`),
  CONSTRAINT `PUSH_CHAT_FK3` FOREIGN KEY (`SENDER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ㅇ 채팅방에 들어와있지 않은 모임참가자들에게 메세지 push.\n ㅇpush 실패하면, 로그인시 못받은 Push 가져가도록 하기.';


-- gogooo_dev.USER_LIKE_MEETING definition

CREATE TABLE `USER_LIKE_MEETING` (
  `USER_ID` int(11) unsigned NOT NULL,
  `MEETING_ID` int(11) unsigned NOT NULL,
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT NULL,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`USER_ID`,`MEETING_ID`),
  KEY `LikeMeeting_MeetingId` (`MEETING_ID`),
  CONSTRAINT `USER_LIKE_MEETING_FK` FOREIGN KEY (`MEETING_ID`) REFERENCES `MEETING` (`ID`),
  CONSTRAINT `USER_LIKE_MEETING_FK_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- gogooo_dev.USER_MEETING definition

CREATE TABLE `USER_MEETING` (
  `MEETING_ID` int(11) unsigned NOT NULL,
  `USER_ID` int(11) unsigned NOT NULL,
  `SIGN_UP_DTTM` datetime DEFAULT current_timestamp(),
  `WITHDRAWAL_DTTM` datetime DEFAULT NULL,
  `ALT_TPCD` char(1) DEFAULT '1',
  `LAST_MODFR_NO` int(11) DEFAULT NULL,
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`MEETING_ID`,`USER_ID`),
  KEY `MeetingUser_UserId` (`USER_ID`),
  CONSTRAINT `USER_MEETING_FK` FOREIGN KEY (`MEETING_ID`) REFERENCES `MEETING` (`ID`),
  CONSTRAINT `USER_MEETING_FK_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='1. 모임 참석했다가 취소시 \n => withdrawal=현재시간, alt_tpcd=3 으로 update\n2. 모임 취소했다가 다시 참여할 경우\n=> 기존 alt_tpcd=3 내역 Delete, 신규 내역 insert';


-- gogooo_dev.CHAT definition

CREATE TABLE `CHAT` (
  `MEETING_ID` int(11) unsigned NOT NULL,
  `MESSAGE_ID` int(11) unsigned NOT NULL,
  `SENDER_ID` int(11) unsigned DEFAULT NULL,
  `PHOTO_YN` tinyint(1) DEFAULT NULL,
  `PAYLOAD` varchar(2000) DEFAULT NULL,
  `INPUT_DTTM` int(11) DEFAULT NULL,
  `ALT_TPCD` char(1) DEFAULT '1',
  `FIRST_REGI_DTTM` datetime DEFAULT current_timestamp(),
  `LAST_MODF_DTTM` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`MEETING_ID`,`MESSAGE_ID`),
  KEY `CHAT_FK_1` (`SENDER_ID`),
  CONSTRAINT `CHAT_FK` FOREIGN KEY (`MEETING_ID`) REFERENCES `MEETING` (`ID`),
  CONSTRAINT `CHAT_FK_1` FOREIGN KEY (`SENDER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ㅇ 채팅에서 발생하는 데이터 보관.\n ㅇDB 용량을 고려하여, 배치로 7일이 지난 데이터는 영구삭제';
